/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministracionRouteImport } from './routes/administracion'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ExpedienteRouteImport } from './routes/expediente'
import { Route as NuevaActuacionRouteImport } from './routes/nueva-actuacion'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PendientesRouteImport } from './routes/pendientes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionRoute = AdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedienteRoute = ExpedienteRouteImport.update({
  id: '/expediente',
  path: '/expediente',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaActuacionRoute = NuevaActuacionRouteImport.update({
  id: '/nueva-actuacion',
  path: '/nueva-actuacion',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PendientesRoute = PendientesRouteImport.update({
  id: '/pendientes',
  path: '/pendientes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRoute
  '/buscar': typeof BuscarRoute
  '/documentos': typeof DocumentosRoute
  '/expediente': typeof ExpedienteRoute
  '/nueva-actuacion': typeof NuevaActuacionRoute
  '/panel': typeof PanelRoute
  '/pendientes': typeof PendientesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRoute
  '/buscar': typeof BuscarRoute
  '/documentos': typeof DocumentosRoute
  '/expediente': typeof ExpedienteRoute
  '/nueva-actuacion': typeof NuevaActuacionRoute
  '/panel': typeof PanelRoute
  '/pendientes': typeof PendientesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRoute
  '/buscar': typeof BuscarRoute
  '/documentos': typeof DocumentosRoute
  '/expediente': typeof ExpedienteRoute
  '/nueva-actuacion': typeof NuevaActuacionRoute
  '/panel': typeof PanelRoute
  '/pendientes': typeof PendientesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracion'
    | '/buscar'
    | '/documentos'
    | '/expediente'
    | '/nueva-actuacion'
    | '/panel'
    | '/pendientes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracion'
    | '/buscar'
    | '/documentos'
    | '/expediente'
    | '/nueva-actuacion'
    | '/panel'
    | '/pendientes'
  id:
    | '__root__'
    | '/'
    | '/administracion'
    | '/buscar'
    | '/documentos'
    | '/expediente'
    | '/nueva-actuacion'
    | '/panel'
    | '/pendientes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracionRoute: typeof AdministracionRoute
  BuscarRoute: typeof BuscarRoute
  DocumentosRoute: typeof DocumentosRoute
  ExpedienteRoute: typeof ExpedienteRoute
  NuevaActuacionRoute: typeof NuevaActuacionRoute
  PanelRoute: typeof PanelRoute
  PendientesRoute: typeof PendientesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion': {
      id: '/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AdministracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expediente': {
      id: '/expediente'
      path: '/expediente'
      fullPath: '/expediente'
      preLoaderRoute: typeof ExpedienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-actuacion': {
      id: '/nueva-actuacion'
      path: '/nueva-actuacion'
      fullPath: '/nueva-actuacion'
      preLoaderRoute: typeof NuevaActuacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendientes': {
      id: '/pendientes'
      path: '/pendientes'
      fullPath: '/pendientes'
      preLoaderRoute: typeof PendientesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracionRoute: AdministracionRoute,
  BuscarRoute: BuscarRoute,
  DocumentosRoute: DocumentosRoute,
  ExpedienteRoute: ExpedienteRoute,
  NuevaActuacionRoute: NuevaActuacionRoute,
  PanelRoute: PanelRoute,
  PendientesRoute: PendientesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
